# Site settings
title: candace woodbury
description: customer success manager, dog & outdoor enthusiast
url: "https://candacewoodbury.com"
baseurl: ""

# Author
author:
  name: candace woodbury
  email: hello@candacewoodbury.com
  linkedin: candacewoodbury
  youtube: candacewoodbury

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
navigation:
  - title: connect
    url: /pages/connect
  - title: creatives
    url: /pages/creatives
  - title: field notes
    url: /blog
  - title: gear
    url: /pages/gear

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .jekyll-cache

sass:
  style: compressed
  sass_dir: _sass
